# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: mv dist docs
      #- run: echo 'jdecode.dev' > docs/CNAME
      - run: git add docs
      - run: git config user.email "jdecode@gmail.com"
      - run: git config user.username "jdecode"
      - run: git config user.name "JD Singh"
      - run: git commit -m "GitHub Pages | gh-pages/docs"
      - run: git push -f https://jdecode:${{ secrets.JDECODE_DEV_GITHUB_PAGES }}@github.com/jdecode/jdecode-dev.git main:gh-pages
